stages:
  # - test
  - build
  - deploy

# test project:
#   stage: test
#   image: node
#   script:
#     - yarn install
#     - yarn test


build project:
  stage: build
  image: node
  script:
    - yarn install
    - yarn build

netlify:
  stage: deploy
  image: node
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
