stages:
  - test
  - build

test project:
  stage: test
  image: node:15
  script:
    - yarn install
    - yarn test


build project:
  stage: build
  image: node:15
  script:
    - yarn install
    - yarn build