# Generated by Django 4.1.7 on 2023-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_task_locationoftheactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='locationoftheactivity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
