# Generated by Django 4.1.7 on 2023-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_task_locationoftheactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='locationoftheactivity',
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
